supervisor_started: true
supervisor_enabled: true

supervisor_programs:
  - name: 'superset-gunicorn'
    command: /var/www/superset/supersetvenv/bin/gunicorn  -w 2 -k gevent --timeout 120  -b  0.0.0.0:8080  --limit-request-line 0  --limit-request-field_size 0  "superset.app:create_app()"
    state: present
    configuration: |
      autostart=true
      autorestart=true
      startretries=1
      startsecs=1
      redirect_stderr=true
      stderr_logfile=/var/log/superset/gunicorn-err.log
      stdout_logfile=/var/log/superset/gunicorn-out.log
      user=root
