build_packages: 
  - build-essential 
  - libssl-dev 
  - libffi-dev 
  - python3-dev 
  - python3-pip 
  - libsasl2-dev 
  - libldap2-dev 
  - libpq-dev
python_depandencies:
  - wheel
  - flask-wtf==0.14.3
  - psycopg2==2.9.1
  - gevent==21.1.2
  - apache-superset==1.2.0