---
nginx_official_repo: True
keep_only_specified: True

vdomain: example.com
nginx_remove_default_vhost: true

nginx_vhosts:
  - listen: "80 default_server"
    server_name: "{{vdomain}} www.{{vdomain}}"
    extra_parameters: |
      location / {
            proxy_pass http://0.0.0.0:8080/;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
            proxy_set_header X-Forwarded-Server $host;
            proxy_set_header X-Forwarded-Host $host;
            proxy_set_header Host $host;
          }